### ISSUE TITLE
Russian characters support

### ISSUE THREAD

**Issue by wikiselev** [sciurius/chordpro#1]
Hi, thanks so much for this piece of software. I have just run it and it looks like with all other chord generators, Russian characters are not displayed correctly in the output pdf. Is the utf-8 support not implemented yet? Are you planning on doing that? Thanks again!

**Comment by sciurius** [comment]
ChordPro fully supports UTF-8 input data, but of course it needs adequate fonts to show the characters. The default fonts are the rather limited 'PDF standard' fonts.
You can change the fonts using the config files. Replace "name" : "Times-Roman" with "file" : "/path/to/font.ttf".

**Comment by wikiselev** [comment]
Great, it worked! Many thanks!

**Comment by wikiselev** [comment]
If anyone is interested, here is my GitHub repo integrated with Travis CI for automated building of my chords: https://github.com/wikiselev/chords

**Comment by sciurius** [comment]
Archived for those who may be interested. Thanks.
