### ISSUE TITLE
transpose questions and b vs #

### ISSUE THREAD

**Issue by wolftune** [sciurius/chordpro#10]
I understand that `-x 7` results in # chord names whereas `-x -5` results in b chord names. What if I want to mix them? In the key of G, bVI should be a Eb (not D#) but 7 should be F# not Gb. If I'm transposing from another key, this doesn't seem possible.

I don't know if there's a programmatic solution easy enough to be worthwhile. Perhaps there's an output that will output transposed source .cho file so that it can then be manually edited? (without having to just manually transpose the whole source file, just the couple spots in question)

**Comment by sciurius** [comment]
You can send output to a .cho file:

chordpro --transpose +4 source.cho --output transposed.cho

Note that you will lose "#" comments from the source.

**Comment by wolftune** [comment]
great thanks, that's good enough
