### ISSUE TITLE
use serif font by default for Roman Numerals

### ISSUE THREAD

**Issue by wolftune** [sciurius/chordpro#12]
Serif font will look much better with Roman Numerals. The chord I is really not clear as a Roman Numeral as a plain line.

**Comment by sciurius** [comment]
If the user wants to use Nashville/Roman, she can insert

{chordfont Times-Roman}

(or something similar) at the front of the song.

I've also added a configuration resource for that:

chordpro --config=nashville ...

**Comment by wolftune** [comment]
great (although it's only RN that should default to serif, not NNS)

**Comment by sciurius** [comment]
There's also a configuration resource 'roman' for RN.
