### ISSUE TITLE
ChordPro website not working

### ISSUE THREAD

**Issue by soundnotation** [sciurius/chordpro#14]
I guess I was the last visitor, but since a couple of minutes [chordpro.org](https://chordpro.org) says "This site can't be reached"

**Comment by nixxcz** [comment]
I've been running into the same issue since about 2 days ago

**Comment by sciurius** [comment]
According to http://downforeveryoneorjustme.com/chordpro.org the site is up and running.

**Comment by soundnotation** [comment]
It was until a few seconds ago when I clicked on [this file](https://www.chordpro.org/chordpro/images/style_default.pdf) from the preset configuration page and it stopped working again

**Comment by sciurius** [comment]
I'm puzzled...
You can get the same information from GitHub, just select the 'Wiki' tab above the page.

**Comment by nixxcz** [comment]
The site is still down for me as well. I've tried pinging it using https://tools.pingdom.com/ - it works a couple of times and then stops.
Try https://tools.pingdom.com/#!/cgoA4B/http://chordpro.org

**Comment by soundnotation** [comment]
I know, I'm just informing you 😉 btw on the configuration overview page here there's a link to the website, that might be good to shift here as well (http://www.chordpro.org/chordpro/config50.schema)

**Comment by sciurius** [comment]
Thanks, modified.

**Comment by sciurius** [comment]
Are there still access problems? Pingdom responds normally now.

**Comment by soundnotation** [comment]
Right now I don't get stuck in any.
