### ISSUE TITLE
All ukulele chord diagram labels have unhelpful asterisk 

### ISSUE THREAD

**Issue by jostoya** [sciurius/chordpro#16]
Ukulele chord diagrams have an asterisk after every chord name. So, D* Cm7* A7*. It doesn't impart information and looks messy. How can the asterisk be suppressed?

**Comment by sciurius** [comment]
The asterisk indicates that a chord is defined by the user and may differ from a built-in definition. However, in the case of chords defined using a configuration file (as is the case with ukulele) the chords should not be marked as user-defined.
I fixed this in the development branch in git, and the fix will be included in the next release.

Thanks for pointing this out.

**Comment by jostoya** [comment]
Thank you so much - that's wonderful!
