### ISSUE TITLE
[Feature request] Inline chord notation

### ISSUE THREAD

**Issue by artutra** [sciurius/chordpro#17]
What about a inline chord notation? Like:
```
Intro: [[C]] [[Am]]
[C]Som[G]e random lyrics
```
So it will be rendered this way:
> Intro: **C** **Am**
>           **C**  **G**
> Some random lyrics

**Comment by sciurius** [comment]
Have you tried something like:

    {c: Intro: [C] [Am]}
    [C]Som[G]e random lyrics

**Comment by artutra** [comment]
I've tried some online chordpro converters with that example, but it only shows as a comment, so it will not highlight or transpose the notes if necessary.

**Comment by artutra** [comment]
Also it would make the notation more customizable and easier to do responsive design like the example:
![chord-inline](https://user-images.githubusercontent.com/15269475/31920355-cf9f15e6-b83e-11e7-89d0-b92640336928.gif)

**Comment by sciurius** [comment]
Having transposable chords in comments is a ChordPro 5 feature. Apparently the online chordpro converters you tried are not yet up to the latest specifications.

Also, I'm not sure what you mean by making the notation more customizable.

**Comment by AnniePerson** [comment]
An interesting idea. The main difference would be that the proposed "inline chord" notation would use the the formatting of the surrounding text (using inline chords also within the title might be useful in some cases) wheras the existing implementation always uses "comment" formatting.
If it existed I would find the one or the other use case for it, but definetely not my main concern.
My priorities would be
1. Convincing Mike Zuber to support more ChordPro V 5 features in MobileSheetsPro, first of all the new start_of_grid / end_of_grid.
2. Some small enhancements of start_of_grid / end_of_grid like first / second ending and something like tehmulti measure repeat signs as shown in Abb. 27-4 of http://www.mu-sig.de/Theorie/Notation/Notation08.htm
3. Basic markup for parts of lyrics e.g. underline, bold or highlight of single words  in a lyrics line

**Comment by AnniePerson** [comment]
multi measure repeats 
https://musescore.org/en/node/3441
https://musescore.org/sites/musescore.org/files/finale%20four-bar.jpg
I'm looking for a nice alternative for things like "repeat first 4 bars", it could help a lot with memorizing chord sequences, see attached screenshot


![lentementmademoiselle](https://user-images.githubusercontent.com/16453666/32690292-c6869730-c6f4-11e7-928a-7af8014e59cc.gif)

**Comment by sciurius** [comment]
Isn't this just a repeat (m. 1-6) with two alternative endings (m. 7-8 and 15-16)?

**Comment by sciurius** [comment]
> The main difference would be that the proposed "inline chord" notation would use the the formatting of the surrounding text (using inline chords also within the title might be useful in some cases) wheras the existing implementation always uses "comment" formatting.

You can set the comment text properties the same as the lyrics.

> Basic markup for parts of lyrics e.g. underline, bold or highlight of single words in a lyrics line

I am considering markdown markup for a future (major) release.
