### ISSUE TITLE
Chords diagrams on the right side

### ISSUE THREAD

**Issue by jrmora** [sciurius/chordpro#19]
This will be another awesome feature:

In order to maximise the space available, I suggest an option to put the chords diagrams on the right instead of the bottom...   (may you help me with that while I'm writing the fingers on built-in chords? )

Thank you,

**Comment by sciurius** [comment]
Interesting suggestion.
Would you envision to have all chords of the song at the right of every page?
How to deal with clashes (when lyrics lines get too long and run into the chords)?
Did you try the preset configuration `modern1`? It is also a space saver under a number of circumstances.

**Comment by jrmora** [comment]
1) & 2)
Most songs come "phrased": I mean, a lyric line ends when the singer take a breath, so, normally the line is not very long.
In other words, songs are not written with "justified text" :D
Thus, at least 99% of the time we have enough space for 2 or 3 columns of chords.
We can define a width for the song and another for the chords section.

3) I have tried it, but that is completely different. With that approach we must look the underlined text and move to the right to find its corresponding chord... crazy!

I have done around 400 songs with this principle and it always works : please take a look to my songbook (attached file)
[CancioneroAcordesSS.pdf](https://github.com/sciurius/chordpro/files/1428620/CancioneroAcordesSS.pdf)

**Comment by sciurius** [comment]
Thanks for the songbook. It gives a good idea what you are aiming at.
I'll take it into consideration.

**Comment by jrmora** [comment]
Great!

**Comment by sciurius** [comment]
Something like this?

http://www.squirrel.nl/pub/xfer/uploads/3Co7R7CGR3IzN0T_ZnMFAYcQ.pdf

**Comment by jrmora** [comment]
That's perfect!

**Comment by sciurius** [comment]
Implemented in git and will be part of the upcoming 0.91 release.

**Comment by jrmora** [comment]
Excellent, thank you
