### ISSUE TITLE
non-Latin (UTF-8) files do not produce PDF

### ISSUE THREAD

**Issue by topchyan** [sciurius/chordpro#20]
PDF's created from non-English source files are created without 
[Катерок.txt](https://github.com/sciurius/chordpro/files/1442754/default.txt)
[Катерок.pdf](https://github.com/sciurius/chordpro/files/1442756/default.pdf)

on my Linux Mint box here's the command I'm using (via SciTE):
chordpro "$(FilePath)" --encoding=UTF-8 --config=/usr/local/share/perl/5.22.1/App/Music/ChordPro/res/config/ukulele.json --output="$(FilePath).pdf" && xreader "$(FilePath).pdf"

**Comment by sciurius** [comment]
If you didnt change the font settings for the texts, ChordPro uses the Times-Roman corefont which has limited support for non-Latin1 characters.

You probably have several Unicode-supporting fonts on your Mint system. I ran your song using the Liberation font, and the output looks fine.

`chordpro -T /usr/share/fonts/liberation/LiberationSerif-Regular.ttf ...`

Note that the path to the font may be different on your system.

See also: https://www.chordpro.org/chordpro/ChordPro-Configuration.html
and https://www.chordpro.org/chordpro/ChordPro-Configuration-PDF.html#fonts

**Comment by topchyan** [comment]
Now it prints (with a slightly different path of /usr/share/fonts/**truetype**/liberation/LiberationSerif-Regular.ttf
However, this is using the same font for everything. What would be the best way for me to create a user config file with reference to all the fonts? I tried modifying the setting

"fontdir" : "/usr/share/fonts/", 

But I am not sure if it is scanning all of the directory recursively for the font names, because I get an error like this:

requested font 'liberationserifregular' not installed  at /usr/local/share/perl/5.22.1/PDF/API2/Resource/Font/CoreFont.pm line 74.

**Comment by sciurius** [comment]
The font handling of the PDF library that ChordPro uses is powerful but not very sophisticated.
As you found out, it is not scanning directories but it uses paths to construct filenames. The entry for text therefore must include the rest of the directories:

    "text" : {
        "file" : "truetype/liberation/LiberationSerif-Regular.ttf",
        ...
     },

Note that you must use `"file"`, not `"name"`. `"name"` is for built-in fonts only.

In a next release I'll change the fontdir to accept an array of path names, e.g.

    "fontdir" : [
        "/usr/share/fonts/liberation",
        "/usr/share/fonts/msttcore",
        ...
    ],

Thanks for your feedback. It helps me improve the program and documentation.

**Comment by topchyan** [comment]
Here's what I used, and I think it is working well

```
"fonts" : {
	    "title" : {
		"file" : "/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf",
		"size" : 18
	    },
	    "subtitle" : {
		"file" : "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
		"size" : 12
	    },
	    "text" : {
		"file" : "/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf",
		"size" : 12
	    },
	    "chord" : {
		"file" : "/usr/share/fonts/truetype/liberation/LiberationSerif-BoldItalic.ttf",
		"size" : 10
	    },
	    "comment" : {
		"file" : "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
		"size" : 12
	    },
	    "tab" : {
		"file" : "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
		"size" : 8
	    },
	    "toc" : {
		"file" : "/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf",
		"size" : 11
	    },
	    "grid" : {
		"file" : "/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf",
		"size" : 12
	    },
	}
```
I am getting more and more interested in this tool. Is there a user group where we can ask questions, share ideas and best practices?

**Comment by sciurius** [comment]
Great, although you could have saved yourself a lot of typing:

        "fontdir" : [ "/usr/share/fonts/truetype/liberation" ],
        "fonts" : {
	    "title" : {
		"file" : "LiberationSerif-Bold.ttf",
		"size" : 18
	    },
	    "subtitle" : {
		"file" : "LiberationSans-Bold.ttf",
		"size" : 12
	    },
	    "text" : {
		"file" : "LiberationSerif-Regular.ttf",
		"size" : 12
	    },
	    "chord" : {
		"file" : "LiberationSerif-BoldItalic.ttf",
		"size" : 10
	    },
	    "comment" : {
		"file" : "LiberationSans-Regular.ttf",
		"size" : 12
	    },
	    "tab" : {
		"file" : "LiberationMono-Regular.ttf",
		"size" : 8
	    },
	    "toc" : {
		"file" : "LiberationSerif-Regular.ttf",
		"size" : 11
	    },
	    "grid" : {
		"file" : "LiberationMono-Bold.ttf",
		"size" : 12
	    },
	}

**Comment by topchyan** [comment]
Good work. Thank you so much!
