### ISSUE TITLE
diagrams placement on a side does not work properly

### ISSUE THREAD

**Issue by topchyan** [sciurius/chordpro#22]
I found this directive in the documentation, copied it into "my.json" config and ran it, but got an error stating that this property is not recognized.

```
    // This style is enabled by setting "diagramscolumn" to a nonzero value.
    // Value is the column position. 
    // "diagramscolumn" : 350,
    "diagramscolumn" :  0,
```

**Comment by sciurius** [comment]
You need version 0.91 of ChordPro to use this feature.
https://www.chordpro.org/chordpro/ChordPro-Reference-RelNotes.html
