### ISSUE TITLE
Diagrams mispositioned (run off the page)

### ISSUE THREAD

**Issue by sciurius** [sciurius/chordpro#24]
[diagramspos.zip](https://github.com/sciurius/chordpro/files/1485909/diagramspos.zip)
[diagramspos.pdf](https://github.com/sciurius/chordpro/files/1485910/diagramspos.pdf)

**Comment by topchyan** [comment]
Thank you, yes, this seems to be an issue with diagrams (either instrument).

**Comment by sciurius** [comment]
The problem turned out to be that the indent setting for lyrics was also applied to the chord diagrams. This is now fixed in dev.
