### ISSUE TITLE
Feature request: diagram box positioning options

### ISSUE THREAD

**Issue by topchyan** [sciurius/chordpro#25]
Currently diagrams can either appear at the bottom of the text or to the right side (via `diagramscolumn` setting in config.) 

It would be desirable to provide flexible positioning for diagrams: top (before song text), bottom (below song text) left or right. Specifying these in a config file is okay, but enabling user to override this for an individual song in a book would be great.

**Comment by topchyan** [comment]
tried it on dev: works really great! I agree that left may not be ideal placement for diagrams in case of Latin or Cyrillic, but for other languages (like Hebrew) reverse may be needed. I don't speak or write in Hebrew, so I can't recommend anything, but if ChordPro format will be enabled to handle right-to-left texts it might be a good idea to `reverse` the layout somehow. This is a "pie in the sky" kind of an idea, so what's there now in dev seems to work great!

**Comment by sciurius** [comment]
You can obtain per-song behaviour with the special (undocumented) directive `{+`...`}`. For example:

    {title: Song with chord diagrams on top}
    {+pdf.diagrams.show: top}
    ... lyrics and so on ...

**Comment by topchyan** [comment]
Great feature, I will try to test it.

**Comment by KeyJoo** [comment]
> tried it on dev: works really great! I agree that left may not be ideal placement for diagrams in case of Latin or Cyrillic

How can I get Cyrillic `my_song.pdf`

**Comment by sciurius** [comment]
Just type cyrillic in the .cho file, and make sure you use fonts that have cyrillic characters.
https://www.chordpro.org/chordpro/FAQ-Unicode-characters.html

**Comment by KeyJoo** [comment]
# Russian is here, but output.pdf is wrong (

![screenshot from 2018-12-03 18-26-11](https://user-images.githubusercontent.com/21124057/49384595-63d00900-f72c-11e8-8aca-631addefbd76.png)

**Comment by KeyJoo** [comment]
I was reading https://www.chordpro.org/chordpro/ChordPro-Configuration-PDF.html#fonts
but not see 
**in preferences:**
-  [ ] :green_heart: "Times-Roman"

> - `text`
> The font used for lyrics texts.
> Default is "Times-Roman" at size 12.

There is three fonts only:
- [x] Monospaced
- [x] Sans Serif
- [x] Serif

**Comment by sciurius** [comment]
The font settings in the preferences dialog are for the editor window only.
If you want specific settings like fonts for the PDF output, you need to do so using a config file.

**Comment by sciurius** [comment]
I think your knowledge of english may be a problem.
Maybe one of the other russian users could chime in and help Vladimir?

**Comment by KeyJoo** [comment]
Johan, thank you very much for answering my questions with patience.
