### ISSUE TITLE
(enhancement) Output [Chords] mixed in with lyrics 

### ISSUE THREAD

**Issue by lpinner** [sciurius/chordpro#28]
As discussed at https://groups.google.com/forum/m/#!msg/chordpro/1Vk8hjtFWsc/_P53824SAwAJ please consider adding the option of outputting [Chords] mixed in with lyrics instead of above. 

It would be useful if the formatting of the [Chords] could be controlled by config options so users can bold/italic/change font type /size to help chords stand out from lyric text.

**Comment by sciurius** [comment]
Thanks for the suggestion. This is now implemented in the `dev` branch and will be part of the next release.

**Comment by lpinner** [comment]
I just tested the dev branch and it works well for the couple of chordpro files I tried.  Thank you.
