### ISSUE TITLE
Better placement of chord diagrams when using columns

### ISSUE THREAD

**Issue by pope1ni** [sciurius/chordpro#32]
Hi,

I see that you've been developing `pdf.diagrams.show`.
Would it be possible to make this work better when using `settings.columns`?

Currently the chord diagrams are drawn inside the columns. So if I have a song over two columns, `top` and `bottom` wrap chord diagrams in the top of the first column and the bottom of the second column respectively, while `right` wedges them between the two columns (in the right of the first column).

Would it be possible for them to be drawn outside of the columns, and possibly even support anchoring them to the bottom of the page above the footer?

**Comment by sciurius** [comment]
The `pdf.diagrams.show` feature is a bit experimental so your feedback is very much appreciated.
There are several aspects of this feature to be sorted out. May I invite you to joun the discussion at
https://groups.google.com/d/msgid/chordpro/61e77b8d-c943-41c4-a72f-49b8824765f2%40googlegroups.com.

**Comment by sciurius** [comment]
Fixed with the implementation of pdf.diagrams.show (values top, bottom, below, right).
