### ISSUE TITLE
Is it possible to omit page breaks?

### ISSUE THREAD

**Issue by Gajusbonus** [sciurius/chordpro#36]
I want the new song to start right after the last one, without a page break. Is this possible?

**Comment by sciurius** [comment]
No.
Maybe you can just continue from one song to the other, and use a {comment} directive to indicate it is a new song?
----
A user community discussing ChordPro can be found at
https://groups.google.com/forum/#!forum/chordpro

**Comment by Gajusbonus** [comment]
Sorry, that does not seem to work. I tried:
cat *.pro > newsong.txt
And rendering this with chordpro just doesn't make any sense of titles, subtitles and page footers.

**Comment by sciurius** [comment]
Continued in the mailing list.
