### ISSUE TITLE
Some more user-friendly build docs?

### ISSUE THREAD

**Issue by wolftune** [sciurius/chordpro#4]
As a chordii user interested in moving to the newer ChordPro, I'm not clear on whether the release is recommended for general use yet and if so, how to build/install/package etc. so I can actually use it (in my case, in Ubuntu)

**Comment by sciurius** [comment]
ChordPro 0.72 is at least as stable and robust as the old program. You can install it with the "cpan" command at the command prompt:

$ cpan chordpro

**Comment by wolftune** [comment]
thanks, that should be added to the readme probably. Something like "To install, clone the repo and run ` cpan chordpro`" or similar.

**Comment by sciurius** [comment]
You can clone the repo, and run scripts/chordpro.pl . This will get you the development version. You may need to install some additional Perl modules.
Alternatively you can install the latest release with "cpan chordpro". This will install /usr/bin/chordpro globally. Dependencies will be handled automatically.

I'll leave this issue open as a reminder to improve the GitHub README. Thanks for pointing this out.

**Comment by wolftune** [comment]
OH!! I've never used cpan before, I didn't realize that I could run it without cloning, I get it now! Yes, this being clear in the docs is ideal. I assume knowing about updates to releases requires manual checking though, right? Otherwise, someone would need to package it in Debian repos or something, right?

**Comment by sciurius** [comment]
I've added some info to the README in the dev branch, but it is far from complete.
Contributions are welcome.

**Comment by wolftune** [comment]
I see. What's the benefits of the cpanm and wxchordpro stuff vs the plain `cpan chordpro` command?

**Comment by sciurius** [comment]
cpanm automatically handles dependencies.
WxChordPro is a GUI wrapper. It is included in ChordPro, but you will need to install some more modules and libraries to use it. When installing WxChordPro with cpanm, installing these dependencies will be done for you. I do not want to bother ChordPro command line users with the GUI stuff, so I moved the GUI dependencies to WxChordPro.

**Comment by wolftune** [comment]
I got this error trying the instructions:

```
Warning: Cannot install App::cpanm, don't know what it is.
Try the command

    i /App::cpanm/
```

I tried just `cpan wxchordpro` and that did a lot, but I saw several error lines in the process. I think ran `sudo apt install cpanminus` (the recommended command when I tried to run cpanm after the original install of that failed). Then I ran `cpanm wxchordpro` but that had this error:

```
Building and testing Alien-wxWidgets-0.67 ... FAIL
! Installing Alien::wxWidgets failed. See /home/aaron/.cpanm/work/1489765412.31397/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Alien::wxWidgets' is not installed
! Bailing out the installation for Wx-0.9928.
! Installing the dependencies failed: Module 'Wx' is not installed
! Bailing out the installation for App-Music-ChordPro-Wx-v0.710.4.
1 distribution installed
```

Incidentally, I had this error at the top:

```
! Can't write to /usr/local/share/perl/5.22.1 and /usr/local/bin: Installing modules to /home/aaron/perl5
! To turn off this warning, you have to do one of the following:
!   - run me as a root or with --sudo option (to install to /usr/local/share/perl/5.22.1 and /usr/local/bin)
!   - Configure local::lib in your existing shell to set PERL_MM_OPT etc.
!   - Install local::lib by running the following commands
!
!         cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
```

So, I'm not succeeding at getting wxchordpro to see what the GUI is.

**Comment by wolftune** [comment]
Besides those notes above, I think it makes sense to have in the README instructions for plain CLI install and *then* say, "if you want a GUI…" for that process.

**Comment by sciurius** [comment]
> Warning: Cannot install App::cpanm 

My fault, this should have been App::cpanminus .

I'm pretty sure debian has packages for all requirements, try apt-get install libwx-perl . This should be sufficient to run WxChordPro.

**Comment by wolftune** [comment]
The App fix worked indeed (so I didn't need to use apt for cpanm), but I'm not sure if the wxchordpro is something that already was installed but built wrong or what or if rerunning the build stuff got that fixed… what I know is that I have it in my path, and when I run wxchordpro, this happens:

```
$ wxchordpro 
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-primary-button-warps-slider' of type `gboolean' from rc file value "((GString*) 0x171f0c0)" of type `gboolean'
Can't locate App/Music/ChordPro/Wx.pm in @INC (you may need to install the App::Music::ChordPro::Wx module) (@INC contains: /usr/local/bin/../lib /usr/local/bin/../CPAN /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/local/share/perl/5.22.1/App/Music/ChordPro/Wx/Main.pm line 18.
BEGIN failed--compilation aborted at /usr/local/share/perl/5.22.1/App/Music/ChordPro/Wx/Main.pm line 18.
Compilation failed in require at /usr/share/perl/5.22/base.pm line 97.
        ...propagated at /usr/share/perl/5.22/base.pm line 106.
BEGIN failed--compilation aborted at /usr/local/bin/wxchordpro line 17.
```

**Comment by sciurius** [comment]
I assumed you were running from the git repo. Can you try running script/wxchordpro.pl ?

BTW: Did you install WxChordPro from CPAN after installing libwx-perl ?

**Comment by wolftune** [comment]
`perl script/wxcohrdpro.pl` worked fine. I wonder if I didn't need to do any of the other things I tried in order to run that way.

I did install with cpanm after installing libwx-perl.

Anyway, I must say that I don't find the GUI valuable at all. It's not really worth my time to play with that more. I think nobody exists who will both want the GUI *and* be willing to follow any sort of CLI build instructions. It's fine to have the GUI as a tool, but the only people who will ever use it will be those who get it because it's packaged for them or something like that.

Anyway, glad this is helping clear up the README, but I'm happy to stick to the CLI from here on. I think it may make sense for the README to only mention installing with `cpan chordpro`. Have a different file if you think any perl developer or distro packager actually needs instructions about building the GUI — no end-user will want to build the GUI themselves.

**Comment by sciurius** [comment]
I'm currently moving the build/install/use documentation to the GitHub  wiki. Would you like to help improving the information?

**Comment by wolftune** [comment]
I would like to help, but I can't promise much as I'm swamped with higher priorities. But once the wiki is started, feel free to ping me. I might offer some edits here and there

**Comment by sciurius** [comment]
https://github.com/sciurius/chordpro/wiki

**Comment by AnniePerson** [comment]
Thanks

 

regards

 

Herbert
 

--
___________________________________
Herbert Schneider
mailto:herbertschneider@gmx.de
http://www.moonlightcrisis.de
http://www.facebook.com/MoonlightCrisis
http://www.frankenbaend.de
http://www.facebook.com/Frankenbaend

 
 

Gesendet: Montag, 19. Juni 2017 um 23:14 Uhr
Von: "Johan Vromans" <notifications@github.com>
An: sciurius/chordpro <chordpro@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [sciurius/chordpro] Some more user-friendly build docs? (#4)


https://github.com/sciurius/chordpro/wiki

**Comment by wolftune** [comment]
Apologies, it's possibly something weird on my end, but I'm not seeing how to edit the wiki. I wanted specifically to edit the page https://github.com/sciurius/chordpro/wiki/ChordPro-Install-on-Linux which needs to better start with the question of wanting CLI or GUI options and then explain each instead of assuming GUI as default. (I'd simply use headers called "GUI version" and "CLI version" and under each mention the pros/cons what each is followed by instructions for each respectively)

Otherwise, the wiki mostly looks fine!

**Comment by sciurius** [comment]
The Wiki was set restricted to collaborators only. I've now allowed public (= github users) access.
