### ISSUE TITLE
chord grids not as nice as chordii

### ISSUE THREAD

**Issue by wolftune** [sciurius/chordpro#5]
The chord grids aren't as nicely designed, for example the open-string marks touch the other lines instead of having a little space

**Comment by sciurius** [comment]
Touching at the bottom, I assume?
I'll add a bit of space.
Thanks for pointing this out.

**Comment by wolftune** [comment]
Yes, that was the issue.

Also, in my rendering on-screen, I'm seeing inconsistency in the line thicknesses in the grids, but I suspect that's a rendering issue and wouldn't look different on printing (didn't check). Maybe the lines aren't as thick as with chordii and that's why it renders differently?

For reference of the various issues:

![grids](https://cloud.githubusercontent.com/assets/2801853/23871430/95315962-07e7-11e7-97c0-6e595fe78aac.png)

Chordii is on the right, looks better in several (but not all) respects (incidentally, it had to be zoomed more to be the same size because chordii's grids were smaller by default)

**Comment by sciurius** [comment]
Fixed in Git.
