### ISSUE TITLE
option to translate # and b to ♯ and ♭

### ISSUE THREAD

**Issue by wolftune** [sciurius/chordpro#9]
This shouldn't change the markup, just the rendering. With an option set and an appropriate font, allow the rendering to substitute these symbols,

(note: I made this separate issue from #6 because this isn't tied to NNS or Roman numerals, it's just something good for any situation)

I'm not sure how to identify which fonts will reliably work, but I know several options are available at least. I guess we need to figure out what's the most common option(s).

**Comment by sciurius** [comment]
Thanks. I move this to a future release.

**Comment by wolftune** [comment]
incidentally, although no rush, I find the regular b letter to look far more awkward when it is the first symbol and next to lowercase numerals such as the roman numeral bii as compared to the more common use in a chord like Db.

**Comment by sciurius** [comment]
See issue #13

**Comment by wolftune** [comment]
This issue contains info that isn't in #13 so I'd suggest leaving it open for someday or copying the emphasis on ♯ and ♭ over there (but I won't argue about it further, whatever you decide to do now)
